language: node_js
node_js: node_js
deploy:
  provider: heroku
  api_key:
    secure: q6a7oWX+Sds1mlaXPXfCcLnsa6oHrBqKAbtrusq8EOtIq0loG5wYiqLGilWwAmk06K4gIavVbS+PkZ2K/W0PwaHCjyFOBtGIw4U82S1YjeDgHuz0PdQRXleQTn9r+nGO5HrviK3K5pjZInQFAf3ZH+hroBQkAPNBmR6Oy2CLb2N6uL9Cr3QUy4OK7QMVb9BiSb18eSUXFw6O5c/QASJCfb+hDVKoUfjFulBEHkcVM+sqz2nG87k0dv3BNNWKG8StOBJ/JYohC/me31hxw/8P+GyXP86pDxu0Ci2gsZXD8Pafaf4Nmq6B0iAjR7bI9QtH609I19BcxAEeOxAT1J4igTM+8btUnNb5T6bvQbuxwk9CgUwkeoX3nnoKZcMyLjHErNnsh/39OA6DoaQqbFjH1xdL5MMosfrJnv8bMXU0WsPyMWX45bnAYda0+K1y4P2Asg+vbBaJh8Dnt5NDDDuCgSfK42/8udRyFV0DC03kXdjnS54FoCp34ZQGpeKLp61PFEXqJIo65B50ylsoX7W1lqKCi/trLAmjn6zQwgvr7s2576i1y2hxZn+5zu3pOdFXUChH7vO1CXe3mjeH0ciAjMrtavDbXNzu/mtU2mxzfM0oAYP2+4Gw4HBOUWZ6MFov9AnTJwRLYmsZlInsbaf1H2AJyfZalkIMGIe0lQ4Uubc=
  app: blogAPI
  on:
    repo: jangusff/blogAPI
