language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: mIljV8xSHDu4EPHIN8Kh4buTCF1KaI4W1GqKoJgedlwdeu2htNbibhSgcYcQUWPNAbySYb2tiG0/zahzt5jVbOAYsdhl6EWZjPNav7SevEDJeuCXSuCDEEyr22CRDC0yErKvbxQpKNUzNu0XfzfwDReUbIR1YEJfioTq2ww9FLwyd3HUq4EFUQjGGsIS4NDDUg4Iz9MUEy+FFJYva0vBOfrNziMJQl5XCBk93H5rlGKVdyWQQJtxb7268ezJFhdBeejD98TLXsqm62uCdhA6JGv9W4iJKOQZlzwqQ3x70Hj18Nan3ZLnRlap07JWb6g77HIXLh+RFKfmOl3U2CNMNDd32GRt0mIYIxjiVPzbz1O/9dva1LBPvVNGWfDorMPSbZdR0xPnqd0cm0xdQ5xHSCFx2aMIpJHG7Usi6iL4zCOHkR0RFdljbv6RjYWxKHxYhKoESe6O0zONAhM1M3DBMtAAhs2ONSL2aAD8oilr7yCeRgSok2vOCzyYqbSvi7sWMX+U9G1umlNubArzccoBaZmht+cOPf/cGDAN+HRS+xEnoWudEcJ0mpoOlPViXI0CaYfF3+6Xs39AzW3Ihk1fIOro/EcQLvLE38dVIuBfHAm2yFpCm55Z2ADuAkkSlpxIRNsbtEit51wJ0TdrVzmnez2cyIL6epEV7Dk/h4MSX/s=
  app: hidden-tor-87773
  on:
    repo: jangusff/blogAPI
